version: "3.2"
services:

  api-gateway:
    image: bgornicki/engrave-api-gateway
    deploy:
      replicas: 1
    ports:
      - 3002:3000
      - 3003:3001
    volumes:
      - ./engrave-api-gateway/src:/app/src
      - ./engrave-api-gateway/dist:/app/dist
    environment:
      - WAIT_HOSTS=mongo:27017,redis:6379
      - BLOGS_DOMAINS=["engrave.website", "engrave.site", "dblog.org"]
    secrets:
      - JWT_SECRET

  ssl:
    image: bgornicki/engrave-ssl
    depends_on:
      - mongo
    ports:
      - 3004:3000
      - 3005:3001
    volumes:
      - ./engrave-ssl/src:/app/src
      - ./engrave-ssl/dist:/app/dist
      - nginx_certs:/etc/letsencrypt
      - certbot:/app/certbot
    environment:
      - SSL_EMAIL=engrave@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - WAIT_HOSTS=mongo:27017
      - SERVER_IP=127.0.0.1

  nginx-configurator:
    image: bgornicki/engrave-nginx-configurator
    ports:
      - 3006:3000
      - 3007:3001
    environment:
      - WAIT_HOSTS=mongo:27017
    volumes:
      - ./engrave-nginx-configurator/src:/app/src
      - ./engrave-nginx-configurator/dist:/app/dist
      - nginx_conf:/etc/nginx/conf.d

  statistics:
    image: bgornicki/engrave-statistics
    depends_on:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017,redis:6379

  blockchain-tracker:
    image: bgornicki/engrave-blockchain-tracker
    depends_on:
      - redis
    ports:
      - 3012:3001
    environment:
      - STARTING_BLOCK=29543648
      - WAIT_HOSTS=redis:6379
    volumes:
      - ./engrave-blockchain-tracker/src:/app/src
      - ./engrave-blockchain-tracker/dist:/app/dist

  blogs-renderer:
    image: bgornicki/engrave-blogs-renderer
    ports:
      - 80:8080
      - 3010:3001
    depends_on:
      - redis
    environment:
      - WAIT_HOSTS=mongo:27017,redis:6379
      - DOMAIN=engrave.website
      - AUTH_SERVICE=http://127.0.0.1:3013
    volumes:
      - certbot:/app/certbot
      - ./engrave-blogs-renderer/src:/app/src
      - ./engrave-blogs-renderer/dist:/app/dist
    secrets:
      - VAULT_TOKEN

  image-uploader:
    image: bgornicki/engrave-image-uploader
    ports:
      - 3000:3000
      - 3001:3001
    secrets:
      - IMGUR_KEY
      - IMGUR_CLIENT_ID
    volumes:
      - ./engrave-image-uploader/src:/app/src
      - ./engrave-image-uploader/dist:/app/dist
  
  beta-dashboard:
    image: bgornicki/engrave-dashboard:latest

  engrave-front-dashboard:
    image: bgornicki/engrave-front-dashboard
    ports:
      - 9229:9229
      - 8080:80
    environment:
      - STEEMCONNECT_REDIRECT_URI=http://127.0.0.1:8080/authorize/
      - PAYMENT_REDIRECT_URI=http://127.0.0.1:8080/dashboard/configure/
      - DOMAIN=engrave.website
      - SSL_EMAIL=engrave@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - BLOGS_DOMAINS=["engrave.website", "engrave.site"]
      - BLOGS_CATEGORIES=["Other", "Financial and economy", "Lifestyle", "Food", "Sport", "Travel", "Health and beauty", "Hobby", "Music", "Journalism", "Photography", "Technology"]
      - WAIT_HOSTS=mongo:27017,redis:6379
      - SERVER_IP=139.162.185.235
      - NAMECOM_API=api.dev.name.com
      - DOMAIN_PRICE_SBD=10
      - DOMAIN_PRICE_STEEM=20
      - FRONT=engrave
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
      - ./engrave-blogs-renderer/src/themes:/app/themes
      - ./engrave-front-dashboard/src:/app/src
      - ./engrave-front-dashboard/views:/app/views
      - ./engrave-front-dashboard/public:/app/public
      - ./engrave-front-dashboard/dist:/app/dist
    depends_on:
      - mongo
    secrets:
      - NAMECOM_TOKEN
      - NAMECOM_USERNAME
  
  auth:
    image: bgornicki/engrave-auth
    deploy:
      replicas: 1
    ports:
      - 3013:3000
      - 3014:3001
    volumes:
      - ./engrave-auth/src:/app/src
      - ./engrave-auth/dist:/app/dist
    environment:
      - WAIT_HOSTS=mongo:27017,redis:6379
      - SC2_REDIRECT_DASHBOARD=http://127.0.0.1:3013/dashboard/authorize
      - SC2_REDIRECT_BLOG=http://127.0.0.1:3013/blog/authorize
      - STEEMCONNECT_ID=engrave.app
      - DASHBOARD_ADDR=http://127.0.0.1:8080
    secrets:
      - SC2_APP_SECRET
      - JWT_SECRET
      - VAULT_TOKEN
  
  mailer:
    image: bgornicki/engrave-mailer
    volumes:
      - ./engrave-mailer/src:/app/src
      - ./engrave-mailer/dist:/app/dist
    environment:
      - MAILGUN_SENDER_NAME=Engrave platform
      - MAILGUN_SENDER_ADDRESS=noreply@engrave.website
    secrets:
      - MAILGUN_DOMAIN
      - MAILGUN_API_KEY
    ports:
      - 3015:3000
      - 3016:3001

  sitemap-builder:
    image: bgornicki/engrave-sitemap-builder
    environment:
      - WAIT_HOSTS=redis:6379
    volumes:
      - ./engrave-sitemap-builder/src:/app/src
      - ./engrave-sitemap-builder/dist:/app/dist
    ports:
      - 3017:3000
      - 3018:3001

  mongo:
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
    - "27017:27017"

  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
    - "6379:6379"
  
  vault:
    image: vault
    ports:
      - 8200:8200
    volumes:
      - vault_db:/vault/file:rw
      - ./vault/config:/vault/config:rw
    entrypoint: vault server -config=/vault/config/vault.json

volumes:
  db-data:
  nginx_certs:
  nginx_conf:
  certbot:
  redis-data:
  vault_db:
 
secrets:
  NAMECOM_TOKEN:
    external: true
  NAMECOM_USERNAME:
    external: true
  IMGUR_KEY:
    external: true
  IMGUR_CLIENT_ID:
    external: true
  SC2_APP_SECRET:
    external: true
  JWT_SECRET:
    external: true
  VAULT_TOKEN:
    external: true
  MAILGUN_DOMAIN:
    external: true
  MAILGUN_API_KEY:
    external: true