version: "3"
services:
  
  nginx:
    image: bgornicki/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
    depends_on:
      - engrave

  engrave:
    image: bgornicki/engrave
    ports:
      - 127.0.0.1:9229:9229
    environment:
      - STEEMCONNECT_REDIRECT_URI=http://127.0.0.1/authorize/
      - DOMAIN=engrave.website
      - SSL_EMAIL=test@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - BLOGS_DOMAINS=["engrave.website", "engrave.site"]
      - BLOGS_CATEGORIES=["Other", "Financial and economy", "Lifestyle", "Food", "Sport", "Travel", "Health and beauty", "Hobby", "Music", "Journalism", "Photography", "Technology"]
      - WAIT_HOSTS=mongo:27017
      - SERVER_IP=139.162.185.235
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - db-data:/data/db

volumes:
  db-data:
  nginx_certs:
  nginx_conf: