FROM nginx

COPY nginx-watch.sh /etc/nginx/

COPY conf/_development.conf /etc/nginx/conf.d/80_engrav.website.conf
COPY conf/default.conf /etc/nginx/conf.d/

#COPY ./conf/* /etc/nginx/conf.d/

# Watch will restart nginx on every change in configuration files caused by ENGRAVE app
WORKDIR /etc/nginx
RUN ./nginx-watch.sh & 

EXPOSE 80
EXPOSE 443